[INFO ] 2024-03-20 02:44:18.759 [main] GenericDao - Testing if logging is working
[INFO ] 2024-03-20 02:46:41.908 [main] GenericDao - Testing if logging is working
[ERROR] 2024-05-02 16:33:45.996 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:33:46.029 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:33:46.046 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:33:46.057 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:33:46.072 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:33:46.088 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:33:46.101 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.TaskDaoTest.setUp(TaskDaoTest.java:16) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
[ERROR] 2024-05-02 16:34:07.295 [main] Database - SQL Exception
java.sql.SQLSyntaxErrorException: Unknown database 'bite_size_test'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:228) ~[java.sql:?]
	at biteSize.persistence.Database.connect(Database.java:60) ~[classes/:?]
	at biteSize.persistence.Database.runSQL(Database.java:88) [classes/:?]
	at biteSize.persistence.UserDaoTest.setUp(UserDaoTest.java:15) [test-classes/:?]
	at junit.framework.TestCase.runBare(TestCase.java:139) [junit-4.12.jar:4.12]
	at junit.framework.TestResult$1.protect(TestResult.java:122) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.runProtected(TestResult.java:142) [junit-4.12.jar:4.12]
	at junit.framework.TestResult.run(TestResult.java:125) [junit-4.12.jar:4.12]
	at junit.framework.TestCase.run(TestCase.java:129) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.runTest(TestSuite.java:252) [junit-4.12.jar:4.12]
	at junit.framework.TestSuite.run(TestSuite.java:247) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) [junit-rt.jar:?]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) [idea_rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55) [junit-rt.jar:?]
